FROM node:16

WORKDIR /opt/next

ARG MYSQL_HOST
ARG MYSQL_PORT
ARG MYSQL_DATABASE
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ENV MYSQL_HOST $MYSQL_HOST
ENV MYSQL_PORT $MYSQL_PORT
ENV MYSQL_DATABASE $MYSQL_DATABASE
ENV MYSQL_USER $MYSQL_USER
ENV MYSQL_PASSWORD $MYSQL_PASSWORD

ARG LDAP_URI
ARG LDAP_ADMIN
ARG LDAP_COMMONNAME
ARG LDAP_ORGANIZATIONAL_ADRESS
ENV LDAP_URI $LDAP_URI
ENV LDAP_ADMIN $LDAP_ADMIN
ENV LDAP_COMMONNAME $LDAP_COMMONNAME
ENV LDAP_ORGANIZATIONAL_ADRESS $LDAP_ORGANIZATIONAL_ADRESS

ARG NEXT_AUTH_SECRET
ARG JWT_SECRET
ENV NEXT_AUTH_SECRET $NEXT_AUTH_SECRET
ENV JWT_SECRET $NEXT_AUTH_SECRET

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

USER node
EXPOSE 3000
CMD ["npm", "start"]
